export const UPDATE_CERTIFICATE_DEFINITION = 'UPDATE_CERTIFICATE_DEFINITION';
export const UPDATE_CERTIFICATE_URL = 'UPDATE_CERTIFICATE_URL';
export const VERIFY_CERTIFICATE = 'VERIFY_CERTIFICATE';
export const VALIDATE_URL_INPUT = 'VALIDATE_URL_INPUT';

export const STEP_VERIFIED = 'STEP_VERIFIED';
export const UPDATE_PARENT_STEP_STATUS = 'UPDATE_PARENT_STEP_STATUS';
