export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CERTIFICATE_DEFINITION = 'UPDATE_CERTIFICATE_DEFINITION';
export const UPLOAD_CERTIFICATE_DEFINITION = 'UPLOAD_CERTIFICATE_DEFINITION';
export const RESET_CERTIFICATE_DEFINITION = 'RESET_CERTIFICATE_DEFINITION';
export const UPDATE_CERTIFICATE_URL = 'UPDATE_CERTIFICATE_URL';
export const VERIFY_CERTIFICATE = 'VERIFY_CERTIFICATE';
export const VALIDATE_URL_INPUT = 'VALIDATE_URL_INPUT';

export const CLEAR_VERIFIED_STEPS = 'CLEAR_VERIFIED_STEPS';
export const STEP_VERIFIED = 'STEP_VERIFIED';
export const UPDATE_PARENT_STEP_STATUS = 'UPDATE_PARENT_STEP_STATUS';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
